AWSTemplateFormatVersion: 2010-09-09
Description: IAM EC2 Role Stack
Parameters:
  WebRoleName:
    Description: Name for WebRole
    Type: String
  WebInstanceProfileName:
    Description: Name for WebInstanceProfile
    Type: String
Resources:
  WebRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"    
      RoleName: !Ref WebRoleName
  WebInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref WebRole       
      InstanceProfileName: !Ref WebInstanceProfileName
Outputs:
  WebInstanceProfile:
    Description: Web Instance Profile
    Value: !Ref WebRoleName
    Export:
      Name: !Ref WebInstanceProfileName
  WebRole:
    Description: WebIam Role
    Value: !Ref WebRole
    Export:
      Name: !Ref WebRoleName
